export interface Question {
    id: string;
    text: string;
    context?: string;        // JSON data shown as context
    contextLabel?: string;   // label for the context block
    choices: string[];       // 4 choices (HTML allowed in code spans)
    correctIndex: number;    // 0-3
    explanation: string;     // explanation (HTML allowed)
    playgroundInput?: string;  // preset JSON for playground
    playgroundExpression?: string; // preset expression for playground
}

export interface Section {
    id: string;
    number: number;
    title: string;
    description: string;
    tags: string[];
    questions: Question[];
}

const section1: Section = {
    id: 'basics',
    number: 1,
    title: 'JSONata基礎',
    description: 'パス式、ワイルドカード、配列アクセス、フィルタリングの基本を学びます。JSONを知っている方なら、ここからJSONataの世界へ。',
    tags: ['パス式', 'ワイルドカード', '配列', 'フィルタ'],
    questions: [
        {
            id: 'b1',
            text: '以下のJSONデータに対して、JSONata式 <code>name</code> を実行した場合の結果は？',
            context: '{\n  "name": "Alice",\n  "age": 30\n}',
            contextLabel: '入力JSON',
            choices: [
                '<code>"Alice"</code>',
                '<code>{"name": "Alice"}</code>',
                '<code>["Alice"]</code>',
                'エラー',
            ],
            correctIndex: 0,
            explanation: 'JSONataでは、単にフィールド名を書くだけでそのフィールドの値を取得できます。XPathの<code>/name</code>と似た概念です。<code>name</code>と書くと最上位の<code>"name"</code>フィールドの値<code>"Alice"</code>が返ります。',
            playgroundInput: '{\n  "name": "Alice",\n  "age": 30\n}',
            playgroundExpression: 'name',
        },
        {
            id: 'b2',
            text: '以下のJSONに対して <code>Address.City</code> はどの値を返す？',
            context: '{\n  "Name": "Taro",\n  "Address": {\n    "City": "Tokyo",\n    "Zip": "100-0001"\n  }\n}',
            contextLabel: '入力JSON',
            choices: [
                '<code>"Tokyo"</code>',
                '<code>{"City": "Tokyo"}</code>',
                '<code>undefined</code>',
                '<code>null</code>',
            ],
            correctIndex: 0,
            explanation: 'ドット記法で入れ子のオブジェクトにアクセスできます。<code>Address.City</code>は<code>Address</code>オブジェクトの中の<code>City</code>フィールドの値を返します。JavaScriptのドット記法と同じ直感で使えます。',
            playgroundInput: '{\n  "Name": "Taro",\n  "Address": {\n    "City": "Tokyo",\n    "Zip": "100-0001"\n  }\n}',
            playgroundExpression: 'Address.City',
        },
        {
            id: 'b3',
            text: '以下の配列データに <code>Numbers[0]</code> を実行したら？',
            context: '{\n  "Numbers": [10, 20, 30, 40]\n}',
            contextLabel: '入力JSON',
            choices: [
                '<code>10</code>',
                '<code>20</code>',
                '<code>[10]</code>',
                'エラー（0-indexedではない）',
            ],
            correctIndex: 0,
            explanation: 'JSONataの配列インデックスは0始まりです。<code>Numbers[0]</code>は最初の要素<code>10</code>を返します。JavaScriptと同様のインデックス指定が使えます。',
            playgroundInput: '{\n  "Numbers": [10, 20, 30, 40]\n}',
            playgroundExpression: 'Numbers[0]',
        },
        {
            id: 'b4',
            text: '以下のデータで <code>Items.name</code> を評価した結果は？',
            context: '{\n  "Items": [\n    {"name": "Apple", "price": 100},\n    {"name": "Banana", "price": 200},\n    {"name": "Cherry", "price": 300}\n  ]\n}',
            contextLabel: '入力JSON',
            choices: [
                '<code>["Apple", "Banana", "Cherry"]</code>',
                '<code>"Apple"</code>（最初の要素のみ）',
                'エラー（配列には直接プロパティアクセスできない）',
                '<code>[{"name": "Apple"}, {"name": "Banana"}, {"name": "Cherry"}]</code>',
            ],
            correctIndex: 0,
            explanation: 'JSONataの強力な機能の1つです。配列の中のオブジェクトに対してフィールド名を指定すると、すべての要素から自動的にそのフィールドを抽出して配列として返します。JavaScriptの<code>.map(item =&gt; item.name)</code>と同じ結果ですが、はるかに簡潔に書けます。',
            playgroundInput: '{\n  "Items": [\n    {"name": "Apple", "price": 100},\n    {"name": "Banana", "price": 200},\n    {"name": "Cherry", "price": 300}\n  ]\n}',
            playgroundExpression: 'Items.name',
        },
        {
            id: 'b5',
            text: 'ワイルドカード <code>*</code> は何を意味する？以下のJSONに <code>Address.*</code> を実行したら？',
            context: '{\n  "Address": {\n    "City": "Osaka",\n    "Zip": "530-0001",\n    "Country": "Japan"\n  }\n}',
            contextLabel: '入力JSON',
            choices: [
                '<code>["Osaka", "530-0001", "Japan"]</code>',
                '<code>{"City": "Osaka", "Zip": "530-0001", "Country": "Japan"}</code>',
                '<code>"Osaka"</code>（最初のプロパティのみ）',
                'エラー',
            ],
            correctIndex: 0,
            explanation: '<code>*</code>ワイルドカードは、オブジェクトのすべてのフィールドの値を配列として返します。<code>Address.*</code>で<code>Address</code>の全プロパティの値が得られます。特定のフィールド名を知らなくても全値を取得したい場合に便利です。',
            playgroundInput: '{\n  "Address": {\n    "City": "Osaka",\n    "Zip": "530-0001",\n    "Country": "Japan"\n  }\n}',
            playgroundExpression: 'Address.*',
        },
        {
            id: 'b6',
            text: 'フィルタ式 <code>Items[price > 150]</code> の結果は？',
            context: '{\n  "Items": [\n    {"name": "Apple", "price": 100},\n    {"name": "Banana", "price": 200},\n    {"name": "Cherry", "price": 300}\n  ]\n}',
            contextLabel: '入力JSON',
            choices: [
                '<code>[{"name":"Banana","price":200},{"name":"Cherry","price":300}]</code>',
                '<code>[200, 300]</code>',
                '<code>[true, true]</code>',
                '<code>{"name": "Banana", "price": 200}</code>（最初の一致のみ）',
            ],
            correctIndex: 0,
            explanation: '<code>[]</code>内に条件式を書くと配列をフィルタリングできます。SQLの<code>WHERE</code>句に相当する機能です。<code>Items[price > 150]</code>は<code>price</code>が150を超える全要素を返します。',
            playgroundInput: '{\n  "Items": [\n    {"name": "Apple", "price": 100},\n    {"name": "Banana", "price": 200},\n    {"name": "Cherry", "price": 300}\n  ]\n}',
            playgroundExpression: 'Items[price > 150]',
        },
        {
            id: 'b7',
            text: '<code>Items[price > 150].name</code> の結果は？（前問と同じデータ）',
            context: '{\n  "Items": [\n    {"name": "Apple", "price": 100},\n    {"name": "Banana", "price": 200},\n    {"name": "Cherry", "price": 300}\n  ]\n}',
            contextLabel: '入力JSON',
            choices: [
                '<code>["Banana", "Cherry"]</code>',
                '<code>[{"name":"Banana"},{"name":"Cherry"}]</code>',
                '<code>"Banana"</code>',
                'エラー (フィルタ後にドットアクセスできない)',
            ],
            correctIndex: 0,
            explanation: 'フィルタとドットアクセスを組み合わせることができます。<code>Items[price > 150]</code>でフィルタした結果に対して<code>.name</code>で名前だけを抽出します。JSONataの醍醐味はこうしたチェーンの簡潔さです。',
            playgroundInput: '{\n  "Items": [\n    {"name": "Apple", "price": 100},\n    {"name": "Banana", "price": 200},\n    {"name": "Cherry", "price": 300}\n  ]\n}',
            playgroundExpression: 'Items[price > 150].name',
        },
        {
            id: 'b8',
            text: 'ソート関数 <code>$sort(Items, function($a,$b){$a.price > $b.price})</code> の結果で最初の要素は？',
            context: '{\n  "Items": [\n    {"name": "Banana", "price": 200},\n    {"name": "Apple", "price": 100},\n    {"name": "Cherry", "price": 300}\n  ]\n}',
            contextLabel: '入力JSON',
            choices: [
                '<code>{"name": "Apple", "price": 100}</code>（昇順）',
                '<code>{"name": "Cherry", "price": 300}</code>（降順）',
                '<code>{"name": "Banana", "price": 200}</code>（変化なし）',
                'エラー',
            ],
            correctIndex: 0,
            explanation: '<code>$sort</code>は配列をソートする組み込み関数です。比較関数で<code>$a.price > $b.price</code>を指定すると、昇順（小→大）にソートされます。JavaScriptの<code>Array.sort()</code>と同様に比較関数を受け取ります。',
            playgroundInput: '{\n  "Items": [\n    {"name": "Banana", "price": 200},\n    {"name": "Apple", "price": 100},\n    {"name": "Cherry", "price": 300}\n  ]\n}',
            playgroundExpression: '$sort(Items, function($a,$b){$a.price > $b.price})',
        },
    ],
};

const section2: Section = {
    id: 'functions',
    number: 2,
    title: 'JSONata関数と変換',
    description: '組み込み関数、条件式、オブジェクト構築を使いこなして、データ変換のパワーを手に入れましょう。',
    tags: ['$string', '$number', '$map', '$filter', '条件式', 'オブジェクト構築'],
    questions: [
        {
            id: 'f1',
            text: '<code>$string(42)</code> の結果は？',
            choices: [
                '<code>"42"</code>',
                '<code>42</code>',
                '<code>"forty-two"</code>',
                'エラー',
            ],
            correctIndex: 0,
            explanation: '<code>$string()</code>は値を文字列に変換する組み込み関数です。数値<code>42</code>が文字列<code>"42"</code>に変換されます。JavaScript の<code>String(42)</code>と同じです。',
            playgroundInput: '{}',
            playgroundExpression: '$string(42)',
        },
        {
            id: 'f2',
            text: '<code>$number("3.14")</code> の結果は？',
            choices: [
                '<code>3.14</code>',
                '<code>"3.14"</code>',
                '<code>3</code>（整数に切り捨て）',
                'エラー',
            ],
            correctIndex: 0,
            explanation: '<code>$number()</code>は文字列を数値に変換します。<code>"3.14"</code>は浮動小数点数<code>3.14</code>になります。',
            playgroundInput: '{}',
            playgroundExpression: '$number("3.14")',
        },
        {
            id: 'f3',
            text: '<code>$sum(Items.price)</code> の結果は？',
            context: '{\n  "Items": [\n    {"name": "Apple", "price": 100},\n    {"name": "Banana", "price": 200},\n    {"name": "Cherry", "price": 300}\n  ]\n}',
            contextLabel: '入力JSON',
            choices: [
                '<code>600</code>',
                '<code>[100, 200, 300]</code>',
                '<code>"600"</code>',
                'エラー',
            ],
            correctIndex: 0,
            explanation: '<code>$sum()</code>は数値配列の合計を計算します。<code>Items.price</code>で各要素の<code>price</code>を配列として取り出し（<code>[100, 200, 300]</code>）、<code>$sum()</code>でその合計<code>600</code>を算出します。',
            playgroundInput: '{\n  "Items": [\n    {"name": "Apple", "price": 100},\n    {"name": "Banana", "price": 200},\n    {"name": "Cherry", "price": 300}\n  ]\n}',
            playgroundExpression: '$sum(Items.price)',
        },
        {
            id: 'f4',
            text: '<code>$count(Items)</code> の結果は？',
            context: '{\n  "Items": [\n    {"name": "Apple"},\n    {"name": "Banana"},\n    {"name": "Cherry"}\n  ]\n}',
            contextLabel: '入力JSON',
            choices: [
                '<code>3</code>',
                '<code>[3]</code>',
                '<code>{"count": 3}</code>',
                '<code>1</code>',
            ],
            correctIndex: 0,
            explanation: '<code>$count()</code>は配列の要素数を返します。<code>Items</code>配列には3要素あるので<code>3</code>が返ります。',
            playgroundInput: '{\n  "Items": [\n    {"name": "Apple"},\n    {"name": "Banana"},\n    {"name": "Cherry"}\n  ]\n}',
            playgroundExpression: '$count(Items)',
        },
        {
            id: 'f5',
            text: '条件式 <code>age >= 20 ? "成人" : "未成年"</code> でage=18のとき、結果は？',
            context: '{\n  "age": 18\n}',
            contextLabel: '入力JSON',
            choices: [
                '<code>"未成年"</code>',
                '<code>"成人"</code>',
                '<code>false</code>',
                'エラー（三項演算子は使えない）',
            ],
            correctIndex: 0,
            explanation: 'JSONataは三項演算子<code>条件 ? 真の値 : 偽の値</code>をサポートしています。<code>18 >= 20</code>は<code>false</code>なので<code>"未成年"</code>が返ります。JavaScriptの三項演算子と同じです。',
            playgroundInput: '{\n  "age": 18\n}',
            playgroundExpression: 'age >= 20 ? "成人" : "未成年"',
        },
        {
            id: 'f6',
            text: 'オブジェクト構築 <code>{"fullName": FirstName & " " & LastName}</code> の結果は？',
            context: '{\n  "FirstName": "Taro",\n  "LastName": "Yamada"\n}',
            contextLabel: '入力JSON',
            choices: [
                '<code>{"fullName": "Taro Yamada"}</code>',
                '<code>"Taro Yamada"</code>',
                '<code>{"fullName": "TaroYamada"}</code>',
                'エラー',
            ],
            correctIndex: 0,
            explanation: 'JSONataでは<code>{ }</code>でオブジェクトを構築でき、値にJSONata式を直接使えます。<code>&</code>は文字列結合演算子です。JavaScriptの<code>+</code>に相当しますが、JSONataでは<code>&</code>を使います。',
            playgroundInput: '{\n  "FirstName": "Taro",\n  "LastName": "Yamada"\n}',
            playgroundExpression: '{"fullName": FirstName & " " & LastName}',
        },
        {
            id: 'f7',
            text: '<code>$map()</code>を使って各priceを2倍にする式は？',
            context: '{\n  "prices": [100, 200, 300]\n}',
            contextLabel: '入力JSON',
            choices: [
                '<code>$map(prices, function($v){$v * 2})</code>',
                '<code>prices.map(x => x * 2)</code>',
                '<code>$transform(prices, *2)</code>',
                '<code>$each(prices, function($v){$v * 2})</code>',
            ],
            correctIndex: 0,
            explanation: '<code>$map(array, function)</code>は配列の各要素に関数を適用して新しい配列を返します。JavaScriptの<code>Array.map()</code>に相当しますが、JSONataの関数構文<code>function($v){式}</code>を使います。結果は<code>[200, 400, 600]</code>です。',
            playgroundInput: '{\n  "prices": [100, 200, 300]\n}',
            playgroundExpression: '$map(prices, function($v){$v * 2})',
        },
        {
            id: 'f8',
            text: '<code>$join(Items.name, ", ")</code> の結果は？',
            context: '{\n  "Items": [\n    {"name": "Apple"},\n    {"name": "Banana"},\n    {"name": "Cherry"}\n  ]\n}',
            contextLabel: '入力JSON',
            choices: [
                '<code>"Apple, Banana, Cherry"</code>',
                '<code>["Apple", "Banana", "Cherry"]</code>',
                '<code>"Apple,Banana,Cherry"</code>',
                'エラー',
            ],
            correctIndex: 0,
            explanation: '<code>$join(array, separator)</code>は文字列配列を指定のセパレータで結合します。<code>Items.name</code>で名前の配列を取得し、<code>", "</code>で結合して1つの文字列にします。JavaScriptの<code>Array.join()</code>と同じです。',
            playgroundInput: '{\n  "Items": [\n    {"name": "Apple"},\n    {"name": "Banana"},\n    {"name": "Cherry"}\n  ]\n}',
            playgroundExpression: '$join(Items.name, ", ")',
        },
    ],
};

const section3: Section = {
    id: 'dynamodb-stepfunctions',
    number: 3,
    title: 'DynamoDB JSON + Step Functions',
    description: 'AWS Step FunctionsでDynamoDB Scanの結果をJSONataで変換し、通常のJSONとして返す実践パターンを学びます。',
    tags: ['DynamoDB JSON', 'Step Functions', '{% %}', '$states', 'Scan変換'],
    questions: [
        {
            id: 'd1',
            text: 'DynamoDB JSONの型記述子で、文字列を表すキーはどれ？',
            context: '{\n  "UserId": {"S": "user-001"},\n  "Age": {"N": "25"},\n  "Active": {"BOOL": true}\n}',
            contextLabel: 'DynamoDB JSON形式',
            choices: [
                '<code>"S"</code>（String）',
                '<code>"STR"</code>',
                '<code>"string"</code>',
                '<code>"T"</code>（Text）',
            ],
            correctIndex: 0,
            explanation: 'DynamoDB JSONでは各属性値に型記述子が付きます。主な型: <code>"S"</code>(String)、<code>"N"</code>(Number ※文字列として格納)、<code>"BOOL"</code>(Boolean)、<code>"L"</code>(List)、<code>"M"</code>(Map)、<code>"NULL"</code>(Null)。通常のJSONとの最大の違いは、この型ラッパーの存在です。',
            playgroundInput: '{\n  "UserId": {"S": "user-001"},\n  "Age": {"N": "25"},\n  "Active": {"BOOL": true}\n}',
            playgroundExpression: 'UserId.S',
        },
        {
            id: 'd2',
            text: 'DynamoDB JSONで数値はどう表現される？<code>Age</code>フィールドの実際の形式は？',
            choices: [
                '<code>{"N": "25"}</code>（文字列として格納）',
                '<code>{"N": 25}</code>（数値として格納）',
                '<code>{"NUM": 25}</code>',
                '<code>{"number": "25"}</code>',
            ],
            correctIndex: 0,
            explanation: 'DynamoDBでは数値（<code>"N"</code>型）も<strong>文字列として</strong>格納されます。これは精度の問題を回避するためです。JSONataで数値として使いたい場合は<code>$number(Age.N)</code>で変換が必要です。',
            playgroundInput: '{\n  "Age": {"N": "25"}\n}',
            playgroundExpression: '$number(Age.N)',
        },
        {
            id: 'd3',
            text: 'DynamoDB Scan結果から通常のJSONに変換するJSONata式として正しいものは？',
            context: '{\n  "Items": [\n    {\n      "UserId": {"S": "user-001"},\n      "Name": {"S": "Alice"},\n      "Age": {"N": "30"}\n    },\n    {\n      "UserId": {"S": "user-002"},\n      "Name": {"S": "Bob"},\n      "Age": {"N": "25"}\n    }\n  ]\n}',
            contextLabel: 'DynamoDB Scan結果',
            choices: [
                '<code>Items.{"id": UserId.S, "name": Name.S, "age": $number(Age.N)}</code>',
                '<code>Items.map(item => ({id: item.UserId, name: item.Name}))</code>',
                '<code>$flatten(Items)</code>',
                '<code>Items[*].{id: UserId, name: Name}</code>',
            ],
            correctIndex: 0,
            explanation: 'JSONataのマッピング構文<code>配列.{新キー: 式}</code>を使うと、各要素を新しいオブジェクトに変換できます。<code>.S</code>で文字列を、<code>$number(.N)</code>で数値を取り出すことで、DynamoDB JSONから通常のJSONに変換できます。<pre>結果:\n[\n  {"id": "user-001", "name": "Alice", "age": 30},\n  {"id": "user-002", "name": "Bob", "age": 25}\n]</pre>',
            playgroundInput: '{\n  "Items": [\n    {\n      "UserId": {"S": "user-001"},\n      "Name": {"S": "Alice"},\n      "Age": {"N": "30"}\n    },\n    {\n      "UserId": {"S": "user-002"},\n      "Name": {"S": "Bob"},\n      "Age": {"N": "25"}\n    }\n  ]\n}',
            playgroundExpression: 'Items.{"id": UserId.S, "name": Name.S, "age": $number(Age.N)}',
        },
        {
            id: 'd4',
            text: 'AWS Step FunctionsでJSONata式を埋め込む際のデリミタは？',
            choices: [
                '<code>{% 式 %}</code>',
                '<code>${ 式 }</code>',
                '<code>{{ 式 }}</code>',
                '<code>${ 式 }$</code>',
            ],
            correctIndex: 0,
            explanation: 'Step FunctionsのASL（Amazon States Language）内でJSONata式を使う場合、<code>{% %}</code>デリミタで囲みます。例: <code>"Output": "{% $states.result.Items %}"</code>。これはJinja2テンプレートに似た構文です。',
            playgroundInput: '{}',
            playgroundExpression: '"{% と %} で囲む"',
        },
        {
            id: 'd5',
            text: 'Step Functionsで<code>QueryLanguage</code>を<code>"JSONata"</code>に設定した場合、従来のJSONPathフィールドはどう変わる？',
            choices: [
                '<code>InputPath/Parameters/ResultPath/ResultSelector/OutputPath</code> の代わりに <code>Arguments</code> と <code>Output</code> を使う',
                '従来のフィールドもそのまま使える',
                '<code>InputPath</code> だけ <code>Input</code> に名前が変わる',
                '<code>JSONata</code> フィールドが追加される',
            ],
            correctIndex: 0,
            explanation: 'JSONataモードでは、5つのJSONPathフィールド（<code>InputPath</code>, <code>Parameters</code>, <code>ResultPath</code>, <code>ResultSelector</code>, <code>OutputPath</code>）が2つのフィールドに集約されます：\n・<code>Arguments</code>: アクションに送るデータをカスタマイズ\n・<code>Output</code>: 結果を変換して出力\nこれにより、ステート定義がはるかにシンプルになります。',
            playgroundInput: '{}',
            playgroundExpression: '"Arguments と Output の2つに集約"',
        },
        {
            id: 'd6',
            text: 'Step Functions内で<code>$states.input</code>は何を参照する？',
            choices: [
                'そのステートに渡された入力データ',
                'ステートマシン全体の初期入力',
                '前のステートの出力',
                'DynamoDBのテーブルデータ',
            ],
            correctIndex: 0,
            explanation: '<code>$states.input</code>はそのステートに渡された生の入力データを参照する予約変数です。他には<code>$states.result</code>（タスク実行結果）、<code>$states.errorOutput</code>（エラー情報）、<code>$states.context</code>（コンテキスト情報）があります。',
            playgroundInput: '{\n  "comment": "$states.input はStep Functions内でのみ利用可能な予約変数です",\n  "example": "{% $states.input.orderId %}"\n}',
            playgroundExpression: 'comment',
        },
        {
            id: 'd7',
            text: 'DynamoDB Scanの結果からAge > 25のユーザーだけを通常JSONで返すJSONata式は？',
            context: '{\n  "Items": [\n    {"UserId":{"S":"u1"},"Name":{"S":"Alice"},"Age":{"N":"30"}},\n    {"UserId":{"S":"u2"},"Name":{"S":"Bob"},"Age":{"N":"20"}},\n    {"UserId":{"S":"u3"},"Name":{"S":"Carol"},"Age":{"N":"28"}}\n  ]\n}',
            contextLabel: 'DynamoDB Scan結果',
            choices: [
                '<code>Items[$number(Age.N) > 25].{"id": UserId.S, "name": Name.S, "age": $number(Age.N)}</code>',
                '<code>$filter(Items, function($v){$v.Age > 25})</code>',
                '<code>Items[Age > 25].{id: UserId, name: Name}</code>',
                '<code>SELECT * FROM Items WHERE Age > 25</code>',
            ],
            correctIndex: 0,
            explanation: 'DynamoDB JSONではAge値が<code>{"N": "25"}</code>形式なので、比較には<code>$number(Age.N)</code>で数値変換が必要です。フィルタと変換を一気に行います：\n<pre>結果:\n[\n  {"id": "u1", "name": "Alice", "age": 30},\n  {"id": "u3", "name": "Carol", "age": 28}\n]</pre>\nこれがStep Functionsの<code>Output</code>フィールドで使えるJSONata式です。Lambda関数なしでDynamoDBデータの変換が完結します。',
            playgroundInput: '{\n  "Items": [\n    {"UserId":{"S":"u1"},"Name":{"S":"Alice"},"Age":{"N":"30"}},\n    {"UserId":{"S":"u2"},"Name":{"S":"Bob"},"Age":{"N":"20"}},\n    {"UserId":{"S":"u3"},"Name":{"S":"Carol"},"Age":{"N":"28"}}\n  ]\n}',
            playgroundExpression: 'Items[$number(Age.N) > 25].{"id": UserId.S, "name": Name.S, "age": $number(Age.N)}',
        },
        {
            id: 'd8',
            text: 'Step Functionsの<code>Assign</code>フィールドの用途は？',
            choices: [
                'ワークフロー変数に値を保存し、後続のステートで再利用する',
                'IAMロールを割り当てる',
                'DynamoDBテーブルにデータを書き込む',
                'ステートに名前を付ける',
            ],
            correctIndex: 0,
            explanation: '<code>Assign</code>フィールドはJSONataモードで導入された機能で、ワークフロー変数に値を保存できます。例えば<code>"Assign": {"userId": "{% $states.input.id %}"}</code>として保存した変数は、後続のステートで<code>$userId</code>として参照できます。',
            playgroundInput: '{\n  "Assign_example": {\n    "userId": "{% $states.input.id %}",\n    "timestamp": "{% $now() %}"\n  },\n  "comment": "後続ステートで $userId として参照可能"\n}',
            playgroundExpression: 'comment',
        },
    ],
};

export const sections: Section[] = [section1, section2, section3];
